[pytest]
pythonpath = .
markers =
    data_utils: tests related to data utilities
    create: tests related to create operations
    read: tests related to read operations
    update: tests related to update operations
    delete: tests related to delete operations
    cli_add: tests related to the CLI add command
    cli_list: tests related to the CLI list command
    cli_search_by: tests related to the CLI search-by command
    cli_update: tests related to the CLI update command
    cli_delete: tests related to the CLI delete command
    cli_reset: tests related to the CLI reset command