[pytest]
pythonpath = .
markers =
    create: tests related to create operations
    read: tests related to read operations
    update: tests related to update operations
    delete: tests related to delete operations